[package]
name = "lean-humanproof"
version = "0.1"
lean_version = "leanprover-community/lean:3.33.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "075ff371481316d01bc4785d3f803af6f90a3171"}
